import json

# Load existing drugs
with open('data/tunisian_drugs.json', 'r') as f:
    drugs = json.load(f)

# Add more Tunisian medications
new_drugs = {
    # ANTIBIOTICS
    "Ciprofloxacine 500mg": {
        "name": "Ciprofloxacine",
        "dosage": "500mg",
        "usage": "Antibiotique fluoroquinolone pour infections urinaires, respiratoires et digestives",
        "side_effects": "Nausées, diarrhée, vertiges, tendinite, photosensibilité",
        "instructions": "1 comprimé 2 fois par jour pendant 5-14 jours selon l'infection",
        "warnings": "Éviter l'exposition au soleil. Risque de tendinite.",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    "Azithromycine 500mg": {
        "name": "Azithromycine (Zithromax)",
        "dosage": "500mg",
        "usage": "Antibiotique macrolide pour infections respiratoires, ORL et cutanées",
        "side_effects": "Diarrhée, nausées, douleurs abdominales",
        "instructions": "1 comprimé par jour pendant 3 jours",
        "warnings": "Prendre à distance des antiacides",
        "manufacturer": "Pfizer",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Cefixime 200mg": {
        "name": "Cefixime (Oroken)",
        "dosage": "200mg",
        "usage": "Céphalosporine pour infections ORL, urinaires et respiratoires",
        "side_effects": "Diarrhée, nausées, éruptions cutanées",
        "instructions": "1 comprimé 2 fois par jour",
        "warnings": "Allergie croisée possible avec pénicillines",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Peut être utilisé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Amoxicilline 1g": {
        "name": "Amoxicilline",
        "dosage": "1g",
        "usage": "Antibiotique pénicilline pour infections bactériennes",
        "side_effects": "Diarrhée, nausées, éruptions cutanées",
        "instructions": "1 comprimé 2-3 fois par jour",
        "warnings": "Allergie aux pénicillines",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Clamoxyl 500mg": {
        "name": "Clamoxyl (Amoxicilline)",
        "dosage": "500mg",
        "usage": "Antibiotique pour infections ORL, respiratoires, urinaires",
        "side_effects": "Diarrhée, nausées, réactions allergiques",
        "instructions": "1 gélule 3 fois par jour",
        "warnings": "Allergie aux pénicillines",
        "manufacturer": "GSK",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Ofloxacine 200mg": {
        "name": "Ofloxacine (Oflocet)",
        "dosage": "200mg",
        "usage": "Antibiotique fluoroquinolone pour infections urinaires et respiratoires",
        "side_effects": "Nausées, vertiges, insomnie, tendinite",
        "instructions": "1 comprimé 2 fois par jour",
        "warnings": "Éviter l'exposition au soleil",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    # CARDIOVASCULAR
    "Amlodipine 5mg": {
        "name": "Amlodipine (Amlor)",
        "dosage": "5mg",
        "usage": "Antihypertenseur et anti-angineux",
        "side_effects": "Œdèmes des chevilles, bouffées de chaleur, fatigue",
        "instructions": "1 comprimé par jour",
        "warnings": "Ne pas arrêter brutalement",
        "manufacturer": "Pfizer",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Amlodipine 10mg": {
        "name": "Amlodipine",
        "dosage": "10mg",
        "usage": "Antihypertenseur pour hypertension artérielle sévère",
        "side_effects": "Œdèmes, céphalées, palpitations",
        "instructions": "1 comprimé par jour",
        "warnings": "Surveillance de la tension artérielle",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Atorvastatine 20mg": {
        "name": "Atorvastatine (Tahor)",
        "dosage": "20mg",
        "usage": "Hypocholestérolémiant pour réduire le cholestérol",
        "side_effects": "Douleurs musculaires, troubles digestifs",
        "instructions": "1 comprimé le soir",
        "warnings": "Signaler toute douleur musculaire inexpliquée",
        "manufacturer": "Pfizer",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Contre-indiqué pendant l'allaitement"
    },
    "Simvastatine 20mg": {
        "name": "Simvastatine (Zocor)",
        "dosage": "20mg",
        "usage": "Statine pour réduire le cholestérol LDL",
        "side_effects": "Myalgies, troubles hépatiques",
        "instructions": "1 comprimé le soir",
        "warnings": "Éviter le pamplemousse",
        "manufacturer": "MSD",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Contre-indiqué pendant l'allaitement"
    },
    "Bisoprolol 5mg": {
        "name": "Bisoprolol (Cardensiel)",
        "dosage": "5mg",
        "usage": "Bêta-bloquant pour hypertension et insuffisance cardiaque",
        "side_effects": "Fatigue, bradycardie, extrémités froides",
        "instructions": "1 comprimé par jour le matin",
        "warnings": "Ne pas arrêter brutalement",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Surveillance néonatale nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec précautions"
    },
    "Losartan 50mg": {
        "name": "Losartan (Cozaar)",
        "dosage": "50mg",
        "usage": "Antihypertenseur antagoniste des récepteurs de l'angiotensine II",
        "side_effects": "Vertiges, hyperkaliémie, toux rare",
        "instructions": "1 comprimé par jour",
        "warnings": "Surveiller la fonction rénale et le potassium",
        "manufacturer": "MSD",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    "Ramipril 5mg": {
        "name": "Ramipril (Triatec)",
        "dosage": "5mg",
        "usage": "IEC pour hypertension et protection cardiovasculaire",
        "side_effects": "Toux sèche, hypotension, hyperkaliémie",
        "instructions": "1 comprimé par jour",
        "warnings": "Risque de toux sèche persistante",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    "Furosémide 40mg": {
        "name": "Furosémide (Lasilix)",
        "dosage": "40mg",
        "usage": "Diurétique de l'anse pour œdèmes et hypertension",
        "side_effects": "Déshydratation, hypokaliémie, crampes",
        "instructions": "1 comprimé le matin",
        "warnings": "Surveiller les électrolytes",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Peut diminuer la lactation"
    },
    # DIABETES
    "Metformine 500mg": {
        "name": "Metformine",
        "dosage": "500mg",
        "usage": "Antidiabétique oral de première intention pour diabète type 2",
        "side_effects": "Troubles digestifs, diarrhée, nausées",
        "instructions": "1 comprimé 2-3 fois par jour pendant les repas",
        "warnings": "Arrêter avant examens avec produit de contraste",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Peut être utilisé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Metformine 1000mg": {
        "name": "Metformine",
        "dosage": "1000mg",
        "usage": "Antidiabétique oral pour diabète type 2",
        "side_effects": "Troubles digestifs, acidose lactique rare",
        "instructions": "1 comprimé 2 fois par jour pendant les repas",
        "warnings": "Surveiller la fonction rénale",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Peut être utilisé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Gliclazide 30mg": {
        "name": "Gliclazide (Diamicron)",
        "dosage": "30mg LM",
        "usage": "Sulfamide hypoglycémiant pour diabète type 2",
        "side_effects": "Hypoglycémie, prise de poids",
        "instructions": "1 comprimé par jour au petit-déjeuner",
        "warnings": "Risque d'hypoglycémie, ne pas sauter de repas",
        "manufacturer": "Servier",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Passer à l'insuline pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    "Glibenclamide 5mg": {
        "name": "Glibenclamide (Daonil)",
        "dosage": "5mg",
        "usage": "Sulfamide hypoglycémiant pour diabète type 2",
        "side_effects": "Hypoglycémie, troubles digestifs",
        "instructions": "1 comprimé avant le repas",
        "warnings": "Risque d'hypoglycémie sévère",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué, utiliser l'insuline",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    # GASTRO-INTESTINAL
    "Lansoprazole 30mg": {
        "name": "Lansoprazole (Lanzor)",
        "dosage": "30mg",
        "usage": "IPP pour reflux gastro-œsophagien et ulcères",
        "side_effects": "Céphalées, diarrhée, nausées",
        "instructions": "1 gélule par jour avant le petit-déjeuner",
        "warnings": "Traitement de courte durée recommandé",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Éviter pendant l'allaitement"
    },
    "Pantoprazole 40mg": {
        "name": "Pantoprazole (Inipomp)",
        "dosage": "40mg",
        "usage": "IPP pour ulcères et reflux gastrique",
        "side_effects": "Céphalées, diarrhée, flatulences",
        "instructions": "1 comprimé par jour à jeun",
        "warnings": "Ne pas utiliser au long cours sans avis médical",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Données insuffisantes"
    },
    "Domperidone 10mg": {
        "name": "Dompéridone (Motilium)",
        "dosage": "10mg",
        "usage": "Antiémétique et prokinétique pour nausées et vomissements",
        "side_effects": "Sécheresse buccale, céphalées",
        "instructions": "1 comprimé 3 fois par jour avant les repas",
        "warnings": "Risque cardiaque à fortes doses",
        "manufacturer": "Janssen",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Peut augmenter la lactation"
    },
    "Métoclopramide 10mg": {
        "name": "Métoclopramide (Primpéran)",
        "dosage": "10mg",
        "usage": "Antiémétique pour nausées et vomissements",
        "side_effects": "Somnolence, troubles extrapyramidaux",
        "instructions": "1 comprimé 3 fois par jour avant les repas",
        "warnings": "Durée maximale 5 jours",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Peut être utilisé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Lopéramide 2mg": {
        "name": "Lopéramide (Imodium)",
        "dosage": "2mg",
        "usage": "Antidiarrhéique pour diarrhées aiguës",
        "side_effects": "Constipation, douleurs abdominales",
        "instructions": "2 gélules puis 1 après chaque selle liquide (max 8/jour)",
        "warnings": "Ne pas utiliser en cas de diarrhée sanglante",
        "manufacturer": "Janssen",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Éviter au premier trimestre",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Smecta": {
        "name": "Smecta (Diosmectite)",
        "dosage": "3g sachet",
        "usage": "Pansement digestif pour diarrhées et douleurs digestives",
        "side_effects": "Constipation rare",
        "instructions": "1 sachet 3 fois par jour",
        "warnings": "Prendre à distance des autres médicaments",
        "manufacturer": "Ipsen",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    # RESPIRATORY
    "Salbutamol 100µg": {
        "name": "Salbutamol (Ventoline)",
        "dosage": "100µg/dose",
        "usage": "Bronchodilatateur pour asthme et BPCO",
        "side_effects": "Tremblements, tachycardie, céphalées",
        "instructions": "1-2 bouffées en cas de crise, max 8/jour",
        "warnings": "Consulter si utilisation fréquente",
        "manufacturer": "GSK",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Budésonide 200µg": {
        "name": "Budésonide (Pulmicort)",
        "dosage": "200µg",
        "usage": "Corticoïde inhalé pour asthme",
        "side_effects": "Candidose buccale, voix rauque",
        "instructions": "1-2 bouffées 2 fois par jour",
        "warnings": "Rincer la bouche après utilisation",
        "manufacturer": "AstraZeneca",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Montelukast 10mg": {
        "name": "Montélukast (Singulair)",
        "dosage": "10mg",
        "usage": "Antileucotriène pour asthme et rhinite allergique",
        "side_effects": "Céphalées, troubles du sommeil, troubles psychiatriques rares",
        "instructions": "1 comprimé le soir",
        "warnings": "Signaler tout changement d'humeur",
        "manufacturer": "MSD",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Cétirizine 10mg": {
        "name": "Cétirizine (Zyrtec)",
        "dosage": "10mg",
        "usage": "Antihistaminique pour allergies et rhinite",
        "side_effects": "Somnolence légère, sécheresse buccale",
        "instructions": "1 comprimé par jour",
        "warnings": "Peut causer de la somnolence",
        "manufacturer": "UCB",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Peut être utilisé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Desloratadine 5mg": {
        "name": "Desloratadine (Aerius)",
        "dosage": "5mg",
        "usage": "Antihistaminique non sédatif pour allergies",
        "side_effects": "Fatigue, sécheresse buccale rare",
        "instructions": "1 comprimé par jour",
        "warnings": "Peu de somnolence",
        "manufacturer": "MSD",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Loratadine 10mg": {
        "name": "Loratadine (Clarityne)",
        "dosage": "10mg",
        "usage": "Antihistaminique pour rhinite allergique et urticaire",
        "side_effects": "Céphalées, fatigue rare",
        "instructions": "1 comprimé par jour",
        "warnings": "Antihistaminique non sédatif",
        "manufacturer": "Bayer",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Peut être utilisé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    # PAIN & INFLAMMATION
    "Ibuprofène 400mg": {
        "name": "Ibuprofène (Advil, Nurofen)",
        "dosage": "400mg",
        "usage": "Anti-inflammatoire et antalgique",
        "side_effects": "Troubles digestifs, ulcères gastriques",
        "instructions": "1 comprimé 3 fois par jour pendant les repas",
        "warnings": "Éviter en cas d'ulcère ou d'insuffisance rénale",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué au 3ème trimestre",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Ibuprofène 200mg": {
        "name": "Ibuprofène",
        "dosage": "200mg",
        "usage": "Anti-inflammatoire pour douleurs légères à modérées",
        "side_effects": "Troubles digestifs",
        "instructions": "1-2 comprimés 3 fois par jour",
        "warnings": "Prendre pendant les repas",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué au 3ème trimestre",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Diclofénac 50mg": {
        "name": "Diclofénac (Voltarène)",
        "dosage": "50mg",
        "usage": "AINS pour douleurs articulaires et inflammatoires",
        "side_effects": "Troubles digestifs, risque cardiovasculaire",
        "instructions": "1 comprimé 2-3 fois par jour pendant les repas",
        "warnings": "Éviter utilisation prolongée",
        "manufacturer": "Novartis",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué au 3ème trimestre",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Kétoprofène 100mg": {
        "name": "Kétoprofène (Profénid)",
        "dosage": "100mg",
        "usage": "AINS pour douleurs et inflammations",
        "side_effects": "Troubles digestifs, photosensibilité",
        "instructions": "1 comprimé 2 fois par jour",
        "warnings": "Éviter l'exposition au soleil",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué au 3ème trimestre",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Tramadol 50mg": {
        "name": "Tramadol (Contramal)",
        "dosage": "50mg",
        "usage": "Antalgique opioïde pour douleurs modérées à sévères",
        "side_effects": "Nausées, vertiges, somnolence, constipation",
        "instructions": "1 gélule toutes les 4-6 heures si nécessaire",
        "warnings": "Risque de dépendance, ne pas conduire",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Éviter pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    "Codéine 30mg": {
        "name": "Codéine",
        "dosage": "30mg",
        "usage": "Antalgique opioïde et antitussif",
        "side_effects": "Constipation, somnolence, nausées",
        "instructions": "1 comprimé toutes les 4-6 heures",
        "warnings": "Risque de dépendance",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Éviter pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Contre-indiqué pendant l'allaitement"
    },
    # NEUROPSYCHIATRY
    "Sertraline 50mg": {
        "name": "Sertraline (Zoloft)",
        "dosage": "50mg",
        "usage": "Antidépresseur ISRS pour dépression et anxiété",
        "side_effects": "Nausées, insomnie, troubles sexuels",
        "instructions": "1 comprimé par jour le matin",
        "warnings": "Effet après 2-4 semaines",
        "manufacturer": "Pfizer",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec précautions"
    },
    "Paroxétine 20mg": {
        "name": "Paroxétine (Deroxat)",
        "dosage": "20mg",
        "usage": "Antidépresseur ISRS pour dépression et troubles anxieux",
        "side_effects": "Nausées, prise de poids, troubles sexuels",
        "instructions": "1 comprimé par jour le matin",
        "warnings": "Ne pas arrêter brutalement",
        "manufacturer": "GSK",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Risque au 3ème trimestre",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec précautions"
    },
    "Escitalopram 10mg": {
        "name": "Escitalopram (Seroplex)",
        "dosage": "10mg",
        "usage": "Antidépresseur ISRS pour dépression et anxiété",
        "side_effects": "Nausées, insomnie, céphalées",
        "instructions": "1 comprimé par jour",
        "warnings": "Effet après 2-4 semaines",
        "manufacturer": "Lundbeck",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec précautions"
    },
    "Alprazolam 0.5mg": {
        "name": "Alprazolam (Xanax)",
        "dosage": "0.5mg",
        "usage": "Anxiolytique benzodiazépine pour anxiété",
        "side_effects": "Somnolence, dépendance, troubles de mémoire",
        "instructions": "0.5-1mg 2-3 fois par jour",
        "warnings": "Risque de dépendance, traitement court",
        "manufacturer": "Pfizer",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Contre-indiqué pendant l'allaitement"
    },
    "Diazépam 5mg": {
        "name": "Diazépam (Valium)",
        "dosage": "5mg",
        "usage": "Anxiolytique et myorelaxant",
        "side_effects": "Somnolence, dépendance, confusion",
        "instructions": "5-10mg 2-3 fois par jour",
        "warnings": "Risque de dépendance",
        "manufacturer": "Roche",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Contre-indiqué pendant l'allaitement"
    },
    "Zolpidem 10mg": {
        "name": "Zolpidem (Stilnox)",
        "dosage": "10mg",
        "usage": "Hypnotique pour insomnie",
        "side_effects": "Somnolence résiduelle, amnésie, somnambulisme",
        "instructions": "1 comprimé au coucher",
        "warnings": "Traitement court (2-4 semaines max)",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Éviter pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    # DERMATOLOGY
    "Bétaméthasone crème": {
        "name": "Bétaméthasone (Diprosone)",
        "dosage": "0.05% crème",
        "usage": "Dermocorticoïde pour eczéma et dermatoses",
        "side_effects": "Atrophie cutanée, vergetures si usage prolongé",
        "instructions": "Appliquer 1-2 fois par jour en couche fine",
        "warnings": "Ne pas utiliser sur le visage longtemps",
        "manufacturer": "MSD",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser sur petites surfaces",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Éviter sur les seins"
    },
    "Aciclovir 200mg": {
        "name": "Aciclovir (Zovirax)",
        "dosage": "200mg",
        "usage": "Antiviral pour herpès",
        "side_effects": "Nausées, céphalées, éruptions",
        "instructions": "1 comprimé 5 fois par jour pendant 5 jours",
        "warnings": "Bien s'hydrater",
        "manufacturer": "GSK",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Peut être utilisé si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Fluconazole 150mg": {
        "name": "Fluconazole (Diflucan)",
        "dosage": "150mg",
        "usage": "Antifongique pour candidoses",
        "side_effects": "Nausées, céphalées, éruptions",
        "instructions": "1 gélule en prise unique",
        "warnings": "Interactions médicamenteuses nombreuses",
        "manufacturer": "Pfizer",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    # VITAMINS & SUPPLEMENTS
    "Vitamine D3 200000UI": {
        "name": "Vitamine D3 (Uvedose)",
        "dosage": "200000 UI",
        "usage": "Supplémentation en vitamine D",
        "side_effects": "Hypercalcémie si surdosage",
        "instructions": "1 ampoule tous les 3 mois",
        "warnings": "Ne pas dépasser les doses",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Recommandé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Recommandé pendant l'allaitement"
    },
    "Fer + Acide folique": {
        "name": "Fer + Acide folique (Tardyferon B9)",
        "dosage": "50mg Fe + 0.35mg B9",
        "usage": "Traitement de l'anémie ferriprive",
        "side_effects": "Constipation, selles noires, nausées",
        "instructions": "1 comprimé par jour",
        "warnings": "Prendre à distance du thé et café",
        "manufacturer": "Pierre Fabre",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Recommandé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Acide folique 5mg": {
        "name": "Acide folique (Spéciafoldine)",
        "dosage": "5mg",
        "usage": "Prévention des malformations du tube neural",
        "side_effects": "Rares",
        "instructions": "1 comprimé par jour",
        "warnings": "Commencer avant la conception",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Essentiel avant et pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Magnésium B6": {
        "name": "Magnésium + Vitamine B6 (Magne B6)",
        "dosage": "48mg Mg + 5mg B6",
        "usage": "Carence en magnésium, crampes, fatigue",
        "side_effects": "Diarrhée à fortes doses",
        "instructions": "2 comprimés 2-3 fois par jour",
        "warnings": "Réduire en cas de diarrhée",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    # OPHTHALMOLOGY
    "Tobramycine collyre": {
        "name": "Tobramycine (Tobrex)",
        "dosage": "0.3% collyre",
        "usage": "Antibiotique ophtalmique pour conjonctivites bactériennes",
        "side_effects": "Irritation oculaire transitoire",
        "instructions": "1-2 gouttes 4 fois par jour pendant 7 jours",
        "warnings": "Ne pas utiliser avec lentilles",
        "manufacturer": "Novartis",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Peut être utilisé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Larmes artificielles": {
        "name": "Larmes artificielles (Refresh)",
        "dosage": "0.5% collyre",
        "usage": "Sécheresse oculaire",
        "side_effects": "Rares",
        "instructions": "1-2 gouttes selon besoin",
        "warnings": "Jeter 1 mois après ouverture",
        "manufacturer": "Allergan",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    # ENT
    "Amoxicilline-Acide clavulanique 1g": {
        "name": "Amoxicilline-Acide clavulanique (Augmentin)",
        "dosage": "1g/125mg",
        "usage": "Antibiotique pour infections ORL et respiratoires résistantes",
        "side_effects": "Diarrhée, nausées, candidose",
        "instructions": "1 comprimé 2 fois par jour pendant les repas",
        "warnings": "Surveiller la fonction hépatique",
        "manufacturer": "GSK",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Peut être utilisé pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Prednisolone 20mg": {
        "name": "Prednisolone (Solupred)",
        "dosage": "20mg",
        "usage": "Corticoïde pour inflammations et allergies sévères",
        "side_effects": "Prise de poids, hyperglycémie, ostéoporose",
        "instructions": "Selon prescription, le matin",
        "warnings": "Ne pas arrêter brutalement",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible à faibles doses"
    },
    "Prednisone 5mg": {
        "name": "Prednisone (Cortancyl)",
        "dosage": "5mg",
        "usage": "Corticoïde anti-inflammatoire",
        "side_effects": "Rétention d'eau, troubles du sommeil",
        "instructions": "Selon prescription médicale",
        "warnings": "Décroissance progressive",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible à faibles doses"
    },
    # UROLOGY
    "Tamsulosine 0.4mg": {
        "name": "Tamsulosine (Omix)",
        "dosage": "0.4mg",
        "usage": "Alpha-bloquant pour hypertrophie prostatique",
        "side_effects": "Hypotension orthostatique, éjaculation rétrograde",
        "instructions": "1 gélule par jour après le petit-déjeuner",
        "warnings": "Se lever lentement",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "NOT_APPLICABLE",
        "pregnancy_info": "Médicament masculin",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Non applicable"
    },
    "Alfuzosine 10mg": {
        "name": "Alfuzosine (Xatral)",
        "dosage": "10mg LP",
        "usage": "Alpha-bloquant pour troubles urinaires prostatiques",
        "side_effects": "Vertiges, hypotension",
        "instructions": "1 comprimé par jour après le dîner",
        "warnings": "Éviter de conduire au début",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "NOT_APPLICABLE",
        "pregnancy_info": "Médicament masculin",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Non applicable"
    },
    # THYROID
    "Lévothyroxine 25µg": {
        "name": "Lévothyroxine (Levothyrox)",
        "dosage": "25µg",
        "usage": "Hormone thyroïdienne pour hypothyroïdie",
        "side_effects": "Palpitations, tremblements si surdosage",
        "instructions": "1 comprimé le matin à jeun",
        "warnings": "Prendre 30 min avant le petit-déjeuner",
        "manufacturer": "Merck",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Essentiel pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Lévothyroxine 75µg": {
        "name": "Lévothyroxine (Levothyrox)",
        "dosage": "75µg",
        "usage": "Hormone thyroïdienne pour hypothyroïdie",
        "side_effects": "Palpitations si surdosage",
        "instructions": "1 comprimé le matin à jeun",
        "warnings": "Surveillance TSH régulière",
        "manufacturer": "Merck",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Ajuster la dose pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Lévothyroxine 100µg": {
        "name": "Lévothyroxine (Levothyrox)",
        "dosage": "100µg",
        "usage": "Hormone thyroïdienne pour hypothyroïdie",
        "side_effects": "Tachycardie, nervosité si surdosage",
        "instructions": "1 comprimé le matin à jeun",
        "warnings": "Surveillance cardiaque chez les personnes âgées",
        "manufacturer": "Merck",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Dose à augmenter pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    # CONTRACEPTION
    "Éthinylestradiol + Lévonorgestrel": {
        "name": "Pilule contraceptive (Minidril)",
        "dosage": "30µg EE + 150µg LNG",
        "usage": "Contraception orale",
        "side_effects": "Nausées, tension mammaire, spotting",
        "instructions": "1 comprimé par jour pendant 21 jours",
        "warnings": "Risque thromboembolique chez fumeuses",
        "manufacturer": "Pfizer",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Préférer progestatifs seuls"
    },
    "Désogestrel 75µg": {
        "name": "Désogestrel (Cerazette)",
        "dosage": "75µg",
        "usage": "Contraception progestative",
        "side_effects": "Spotting, acné, prise de poids",
        "instructions": "1 comprimé par jour en continu",
        "warnings": "Prendre à heure fixe",
        "manufacturer": "MSD",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    # COMMON OTC
    "Doliprane 500mg": {
        "name": "Doliprane (Paracétamol)",
        "dosage": "500mg",
        "usage": "Antalgique et antipyrétique",
        "side_effects": "Rares aux doses recommandées",
        "instructions": "1-2 comprimés toutes les 4-6 heures",
        "warnings": "Maximum 4g par jour",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Dafalgan 1g": {
        "name": "Dafalgan (Paracétamol)",
        "dosage": "1g",
        "usage": "Antalgique et antipyrétique",
        "side_effects": "Hépatotoxicité si surdosage",
        "instructions": "1 comprimé toutes les 6-8 heures",
        "warnings": "Maximum 3g par jour",
        "manufacturer": "UPSA",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Nurofen 400mg": {
        "name": "Nurofen (Ibuprofène)",
        "dosage": "400mg",
        "usage": "Anti-inflammatoire et antalgique",
        "side_effects": "Troubles digestifs",
        "instructions": "1 comprimé 3 fois par jour pendant les repas",
        "warnings": "Éviter si ulcère gastrique",
        "manufacturer": "Reckitt",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué au 3ème trimestre",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Aspégic 100mg": {
        "name": "Aspégic (Aspirine)",
        "dosage": "100mg",
        "usage": "Antiagrégant plaquettaire pour prévention cardiovasculaire",
        "side_effects": "Saignements, troubles digestifs",
        "instructions": "1 sachet par jour",
        "warnings": "Risque hémorragique",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Faibles doses possibles sur avis médical",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible à faibles doses"
    },
    "Gaviscon": {
        "name": "Gaviscon",
        "dosage": "Suspension buvable",
        "usage": "Antiacide pour reflux gastro-œsophagien",
        "side_effects": "Rares",
        "instructions": "1 sachet après les repas et au coucher",
        "warnings": "Contient du sodium",
        "manufacturer": "Reckitt",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Maalox": {
        "name": "Maalox",
        "dosage": "Comprimés à croquer",
        "usage": "Antiacide pour brûlures d'estomac",
        "side_effects": "Constipation ou diarrhée",
        "instructions": "1-2 comprimés après les repas",
        "warnings": "Prendre à distance des autres médicaments",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Strepsils": {
        "name": "Strepsils",
        "dosage": "Pastilles",
        "usage": "Antiseptique pour maux de gorge",
        "side_effects": "Rares",
        "instructions": "1 pastille toutes les 2-3 heures",
        "warnings": "Ne pas dépasser 8 pastilles par jour",
        "manufacturer": "Reckitt",
        "country": "Tunisia",
        "pregnancy_category": "SAFE",
        "pregnancy_info": "Sûr pendant la grossesse",
        "breastfeeding_safe": True,
        "breastfeeding_info": "Compatible avec l'allaitement"
    },
    "Rhinofluimucil": {
        "name": "Rhinofluimucil",
        "dosage": "Spray nasal",
        "usage": "Décongestionnant nasal pour rhinite",
        "side_effects": "Sécheresse nasale, effet rebond",
        "instructions": "1-2 pulvérisations 3-4 fois par jour",
        "warnings": "Maximum 5 jours d'utilisation",
        "manufacturer": "Zambon",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Éviter pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    "Actifed": {
        "name": "Actifed",
        "dosage": "Comprimés",
        "usage": "Décongestionnant pour rhume et rhinite",
        "side_effects": "Somnolence, sécheresse buccale",
        "instructions": "1 comprimé 3 fois par jour",
        "warnings": "Peut causer de la somnolence",
        "manufacturer": "GSK",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Éviter pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    "Humex": {
        "name": "Humex Rhume",
        "dosage": "Comprimés jour/nuit",
        "usage": "Traitement symptomatique du rhume",
        "side_effects": "Somnolence (comprimés nuit)",
        "instructions": "Jour: 1 comprimé 3 fois. Nuit: 1 comprimé au coucher",
        "warnings": "Ne pas conduire avec comprimés nuit",
        "manufacturer": "UPSA",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Éviter pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Déconseillé pendant l'allaitement"
    },
    # MUSCLE RELAXANTS
    "Thiocolchicoside 4mg": {
        "name": "Thiocolchicoside (Coltramyl)",
        "dosage": "4mg",
        "usage": "Myorelaxant pour contractures musculaires",
        "side_effects": "Somnolence, diarrhée",
        "instructions": "1 comprimé 2 fois par jour",
        "warnings": "Traitement court (7 jours max)",
        "manufacturer": "Sanofi",
        "country": "Tunisia",
        "pregnancy_category": "AVOID",
        "pregnancy_info": "Contre-indiqué pendant la grossesse",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Contre-indiqué pendant l'allaitement"
    },
    "Méthocarbamol 500mg": {
        "name": "Méthocarbamol (Lumirelax)",
        "dosage": "500mg",
        "usage": "Myorelaxant pour douleurs musculaires",
        "side_effects": "Somnolence, vertiges",
        "instructions": "2 comprimés 3 fois par jour",
        "warnings": "Peut causer de la somnolence",
        "manufacturer": "Various",
        "country": "Tunisia",
        "pregnancy_category": "CAUTION",
        "pregnancy_info": "Utiliser uniquement si nécessaire",
        "breastfeeding_safe": False,
        "breastfeeding_info": "Données insuffisantes"
    },
}

# Merge with existing drugs
drugs.update(new_drugs)

# Save updated database
with open('data/tunisian_drugs.json', 'w', encoding='utf-8') as f:
    json.dump(drugs, f, ensure_ascii=False, indent=2)

print(f"Database updated! Total drugs: {len(drugs)}")
