import json

with open('data/tunisian_drugs.json', 'r', encoding='utf-8') as f:
    drugs = json.load(f)

more_drugs = {
    # More antibiotics
    "Rovamycine 3MUI": {"name": "Spiramycine (Rovamycine)", "dosage": "3 MUI", "usage": "Antibiotique macrolide pour infections ORL et dentaires", "side_effects": "Nausées, diarrhée", "instructions": "1 comprimé 2-3 fois par jour", "warnings": "Prendre pendant les repas", "manufacturer": "Sanofi", "country": "Tunisia", "pregnancy_category": "SAFE", "pregnancy_info": "Sûr pendant la grossesse", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    "Bactrim Forte": {"name": "Cotrimoxazole (Bactrim)", "dosage": "800/160mg", "usage": "Antibiotique pour infections urinaires et respiratoires", "side_effects": "Éruptions cutanées, troubles digestifs", "instructions": "1 comprimé 2 fois par jour", "warnings": "Boire beaucoup d'eau", "manufacturer": "Roche", "country": "Tunisia", "pregnancy_category": "AVOID", "pregnancy_info": "Contre-indiqué pendant la grossesse", "breastfeeding_safe": False, "breastfeeding_info": "Déconseillé pendant l'allaitement"},
    "Érythromycine 500mg": {"name": "Érythromycine", "dosage": "500mg", "usage": "Antibiotique macrolide", "side_effects": "Troubles digestifs", "instructions": "1 comprimé 4 fois par jour", "warnings": "Prendre à jeun", "manufacturer": "Various", "country": "Tunisia", "pregnancy_category": "SAFE", "pregnancy_info": "Sûr pendant la grossesse", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    "Doxycycline 100mg": {"name": "Doxycycline", "dosage": "100mg", "usage": "Antibiotique tétracycline pour infections diverses", "side_effects": "Photosensibilité, troubles digestifs", "instructions": "1 comprimé par jour", "warnings": "Éviter le soleil", "manufacturer": "Various", "country": "Tunisia", "pregnancy_category": "AVOID", "pregnancy_info": "Contre-indiqué pendant la grossesse", "breastfeeding_safe": False, "breastfeeding_info": "Contre-indiqué pendant l'allaitement"},
    "Gentamicine 80mg": {"name": "Gentamicine", "dosage": "80mg injectable", "usage": "Antibiotique aminoside pour infections sévères", "side_effects": "Néphrotoxicité, ototoxicité", "instructions": "Selon prescription médicale", "warnings": "Surveillance rénale et auditive", "manufacturer": "Various", "country": "Tunisia", "pregnancy_category": "CAUTION", "pregnancy_info": "Utiliser uniquement si nécessaire", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    
    # More cardiovascular
    "Clopidogrel 75mg": {"name": "Clopidogrel (Plavix)", "dosage": "75mg", "usage": "Antiagrégant plaquettaire", "side_effects": "Saignements, ecchymoses", "instructions": "1 comprimé par jour", "warnings": "Arrêter avant chirurgie", "manufacturer": "Sanofi", "country": "Tunisia", "pregnancy_category": "CAUTION", "pregnancy_info": "Utiliser uniquement si nécessaire", "breastfeeding_safe": False, "breastfeeding_info": "Déconseillé pendant l'allaitement"},
    "Digoxine 0.25mg": {"name": "Digoxine", "dosage": "0.25mg", "usage": "Cardiotonique pour insuffisance cardiaque", "side_effects": "Nausées, troubles visuels", "instructions": "1 comprimé par jour", "warnings": "Marge thérapeutique étroite", "manufacturer": "Various", "country": "Tunisia", "pregnancy_category": "CAUTION", "pregnancy_info": "Utiliser uniquement si nécessaire", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    "Amiodarone 200mg": {"name": "Amiodarone (Cordarone)", "dosage": "200mg", "usage": "Antiarythmique", "side_effects": "Dysthyroïdie, photosensibilité", "instructions": "Selon prescription", "warnings": "Surveillance thyroïdienne", "manufacturer": "Sanofi", "country": "Tunisia", "pregnancy_category": "AVOID", "pregnancy_info": "Contre-indiqué pendant la grossesse", "breastfeeding_safe": False, "breastfeeding_info": "Contre-indiqué pendant l'allaitement"},
    "Valsartan 80mg": {"name": "Valsartan (Tareg)", "dosage": "80mg", "usage": "Antihypertenseur ARA II", "side_effects": "Vertiges, hyperkaliémie", "instructions": "1 comprimé par jour", "warnings": "Surveiller potassium", "manufacturer": "Novartis", "country": "Tunisia", "pregnancy_category": "AVOID", "pregnancy_info": "Contre-indiqué pendant la grossesse", "breastfeeding_safe": False, "breastfeeding_info": "Déconseillé pendant l'allaitement"},
    "Enalapril 20mg": {"name": "Enalapril (Renitec)", "dosage": "20mg", "usage": "IEC pour hypertension", "side_effects": "Toux sèche, hypotension", "instructions": "1 comprimé par jour", "warnings": "Risque de toux", "manufacturer": "MSD", "country": "Tunisia", "pregnancy_category": "AVOID", "pregnancy_info": "Contre-indiqué pendant la grossesse", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    # More gastro
    "Ranitidine 150mg": {"name": "Ranitidine (Azantac)", "dosage": "150mg", "usage": "Anti-H2 pour ulcères et reflux", "side_effects": "Céphalées, constipation", "instructions": "1 comprimé 2 fois par jour", "warnings": "Retiré dans certains pays", "manufacturer": "GSK", "country": "Tunisia", "pregnancy_category": "SAFE", "pregnancy_info": "Peut être utilisé pendant la grossesse", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    "Phosphalugel": {"name": "Phosphalugel", "dosage": "Gel buvable", "usage": "Antiacide pour brûlures d'estomac", "side_effects": "Constipation", "instructions": "1-2 sachets après les repas", "warnings": "Prendre à distance des autres médicaments", "manufacturer": "Various", "country": "Tunisia", "pregnancy_category": "SAFE", "pregnancy_info": "Sûr pendant la grossesse", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    "Duphalac": {"name": "Lactulose (Duphalac)", "dosage": "Sirop", "usage": "Laxatif osmotique pour constipation", "side_effects": "Ballonnements, flatulences", "instructions": "15-30ml par jour", "warnings": "Effet après 24-48h", "manufacturer": "Abbott", "country": "Tunisia", "pregnancy_category": "SAFE", "pregnancy_info": "Sûr pendant la grossesse", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    "Forlax 10g": {"name": "Macrogol (Forlax)", "dosage": "10g sachet", "usage": "Laxatif osmotique", "side_effects": "Ballonnements", "instructions": "1-2 sachets par jour", "warnings": "Boire beaucoup d'eau", "manufacturer": "Ipsen", "country": "Tunisia", "pregnancy_category": "SAFE", "pregnancy_info": "Sûr pendant la grossesse", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    
    # More neuro/psych
    "Amitriptyline 25mg": {"name": "Amitriptyline (Laroxyl)", "dosage": "25mg", "usage": "Antidépresseur tricyclique", "side_effects": "Somnolence, sécheresse buccale, constipation", "instructions": "1 comprimé le soir", "warnings": "Effet anticholinergique", "manufacturer": "Various", "country": "Tunisia", "pregnancy_category": "CAUTION", "pregnancy_info": "Utiliser uniquement si nécessaire", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec précautions"},
    "Carbamazépine 200mg": {"name": "Carbamazépine (Tégrétol)", "dosage": "200mg", "usage": "Antiépileptique et thymorégulateur", "side_effects": "Somnolence, vertiges, éruptions", "instructions": "Selon prescription", "warnings": "Surveillance hématologique", "manufacturer": "Novartis", "country": "Tunisia", "pregnancy_category": "CAUTION", "pregnancy_info": "Risque tératogène, acide folique recommandé", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec précautions"},
    "Valproate 500mg": {"name": "Valproate (Dépakine)", "dosage": "500mg", "usage": "Antiépileptique", "side_effects": "Prise de poids, tremblements", "instructions": "Selon prescription", "warnings": "Surveillance hépatique", "manufacturer": "Sanofi", "country": "Tunisia", "pregnancy_category": "AVOID", "pregnancy_info": "Contre-indiqué chez femmes en âge de procréer", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec précautions"},
    "Gabapentine 300mg": {"name": "Gabapentine (Neurontin)", "dosage": "300mg", "usage": "Antiépileptique et douleurs neuropathiques", "side_effects": "Somnolence, vertiges", "instructions": "Augmentation progressive", "warnings": "Ne pas arrêter brutalement", "manufacturer": "Pfizer", "country": "Tunisia", "pregnancy_category": "CAUTION", "pregnancy_info": "Utiliser uniquement si nécessaire", "breastfeeding_safe": True, "breastfeeding_info": "Compatible avec l'allaitement"},
    "Rispéridone 2mg": {"name": "Rispéridone (Risperdal)", "dosage": "2mg", "usage": "Antipsychotique atypique", "side_effects": "Prise de poids, somnolence", "instructions": "Selon prescription", "warnings": "Surveillance métabolique", "manufacturer": "Janssen", "country": "Tunisia", "pregnancy_category": "CAUTION", "pregnancy_info": "Utiliser uniquement si nécessaire", "breastfeeding_safe": False, "breastfeeding_info": "Déconseillé pendant l'allaitement"},
    "Olanzapine 10mg": {"name": "Olanzapine (Zyprexa)", "dosage": "10mg", "usage": "Antipsychotique atypique", "side_effects": "Prise de poids importante, diabète", "instructions": "1 comprimé par jour", "warnings": "Surveillance glycémique", "manufacturer": "Lilly", "country": "Tunisia", "pregnancy_category": "CAUTION", "pregnancy_info": "Utiliser uniquement si nécessaire", "breastfeeding_safe": False, "breastfeeding_info": "Déconseillé pendant l'allaitement"},
}